<.table(
  ^.cellpadding := "0",
  ^.cellspacing := "0",
  ^.classes := "poll textPoll ",
  ^.summary="LARA Thai",
  <.tbody(
    <.tr(^.classes := "header date month",
      <.th(^.classes := "nonHeader partCount boldText",
        <.div("2 participants")),
      <.th(^.classes := "xsep", ^.colspan := "1",
        <.div("Boeuf (CH) au curry jaune, lait de coco, pommes de terre et cacahuètes")),
      <.th( ^.classes := "xsep", ^.colspan := "1",
        <.div("Poulet (CH) au curry rouge, lait de coco et courge thaï")),
      <.th( ^.classes := "xsep", ^.colspan := "1",
        <.div("Phat sen ma ma (nouilles jaunes) sautées aux crevettes"))
      <.th( ^.classes := "xsep", ^.colspan := "1",
        <.div("Veg - Tofu sauté aux légumes et graines de soja")),
      <.th( ^.classes := "rsep", ^.colspan := "1",
        <.div("Soupe de nouilles de riz au porc (CH)"))),
    <.tr(),
    <.tr( ^.classes := "participant  partMyself",
      <.td( ^.classes := "pname", ^.id := "part1367130755",
        <.div( ^.classes := "inlineEdit  active",
          <.a( ^.classes := "inlineDeleteIcon", ^.dataid := "1367130755", ^.dataname := "Leon Weber", title="Effacer la saisie", ^.tabindex := "0"),
          <.a( ^.classes := "inlineEditIcon", ^.dataid := "1367130755", ^.title := "Modifier la saisie", ^.tabindex := "0")),
        <.div( ^.classes := "avatarSmall hasMeetMe", ^.data := "leonweber", ^.backgroundImage := "url('https://6a5edc300520d4037dd6-0732807511066685711db213ddc1d2df.ssl.cf2.rackcdn.com/ziiews13v6v78g0ovi81wz4libj4vgn8')"),
        <.div( ^.classes := "pname ", ^.title := "Leon Weber",
          <.a( ^.href := "/leonweber", ^.target := "_blank","Leon Weber"))),
      <.td( ^.classes := "partTableCell n xsep pn", ^.title := "Leon Weber, Boeuf (CH) au curry jaune, lait de coco, pommes de terre et cacahuètes: Non"),
      <.td( ^.classes := "partTableCell y xsep pok", ^.title := "Leon Weber, Poulet (CH) au curry rouge, lait de coco et courge thaï: Oui",
        <.img( ^.alt := "Leon Weber, Poulet (CH) au curry rouge, lait de coco et courge thaï: Oui" ^.classes := "preferenceTick", ^.src := "/builtstatic/1464857356/doodle/graphics/polls/tick_pok.png")),
      <.td( ^.classes := "partTableCell n xsep pn", ^.title := "Leon Weber, Phat sen ma ma (nouilles jaunes) sautées aux crevettes: Non"),
      <.td( ^.classes := "partTableCell n xsep pn", ^.title := "Leon Weber, Veg - Tofu sauté aux légumes et graines de soja: Non"),
      <.td( ^.classes := "partTableCell n sep pn", ^.title := "Leon Weber, Soupe de nouilles de riz au porc (CH): Non")),
    <.tr( ^.classes := "participant ",
      <.td( ^.classes := "pname", ^.id := "part2124972605",
        <.div( ^.classes := "inlineEdit sr-only",
          <.a( ^.classes := "inlineDeleteIcon", ^.dataid := "2124972605", ^.dataname := "Keanu", ^.title := "Effacer la saisie", ^.tabindex := "0"),
          <.a( ^.classes := "inlineEditIcon", ^.dataid := "2124972605", ^.title := "Modifier la saisie", ^.tabindex := "0")),
        <.div( ^.classes := "avatarSmall ", ^.data := "", ^.style := "background-image: url('/builtstatic/1464857356/doodle/graphics/avatar.png')",
        <.div( ^.classes := "gravatar", ^.style := "background-image: url('https://secure.gravatar.com/avatar/?s=30&amp;r=x&amp;d=blank');")),
        <.div( ^.classes := "pname ", ^.title := "Keanu", "Keanu")),
      <.td( ^.classes := "partTableCell n xsep pn", ^.title := "Keanu, Boeuf (CH) au curry jaune, lait de coco, pommes de terre et cacahuètes: Non"),
      <.td( ^.classes := "partTableCell y xsep pok", ^.title := "Keanu, Poulet (CH) au curry rouge, lait de coco et courge thaï: Oui",
        <.img( ^.alt := "Keanu, Poulet (CH) au curry rouge, lait de coco et courge thaï: Oui", ^.classes := "preferenceTick", ^.src := "/builtstatic/1464857356/doodle/graphics/polls/tick_pok.png")),
      <.td( ^.classes := "partTableCell n xsep pn", ^.title := "Keanu, Phat sen ma ma (nouilles jaunes) sautées aux crevettes: Non"),
      <.td( ^.classes := "partTableCell n xsep pn", ^.title := "Keanu, Veg - Tofu sauté aux légumes et graines de soja: Non"),
      <.td( ^.classes := "partTableCell n sep pn", ^.title := "Keanu, Soupe de nouilles de riz au porc (CH): Non")),
    <.tr( ^.classes := "participation yesNo",
      <.td( ^.classes := "pname",
        <.div( ^.width := "182px",
          <.div( ^.classes := "avatarSmall", ^.backgroundImage := "url('https://6a5edc300520d4037dd6-0732807511066685711db213ddc1d2df.ssl.cf2.rackcdn.com/ziiews13v6v78g0ovi81wz4libj4vgn8')"),
          <.label( ^.classes := "hiddenAcc", ^.forid :="pname", ^.title := "l10n_yourName"),
          <.input( ^.classes := "form-control", ^.id := "pname", ^.maxlength :="64", ^.name :="name", ^.placeholder:="Votre nom", ^.tpe :="text", ^.value :=""))),
      <.td( ^.classes := "xsep", ^.data := "0", ^.id := "box0", ^.title := "Boeuf (CH) au curry jaune, lait de coco, pommes de terre et cacahuètes",
        <.label( ^.classes := "hiddenAcc", ^.forid :="option0","Boeuf (CH) au curry jaune, lait de coco, pommes de terre et cacahuètes"),
        <.input( ^.id := "option0", ^.name :="p", ^.tpe :="checkbox")),
      <.td( ^.classes := "xsep", ^.data := "1", ^.id := "box1", ^.title := "Poulet (CH) au curry rouge, lait de coco et courge thaï",
        <.label( ^.classes := "hiddenAcc", ^.forid :="option1","Poulet (CH) au curry rouge, lait de coco et courge thaï"),
        <.input( ^.id := "option1", ^.name :="p", ^.tpe :="checkbox")),
      <.td( ^.classes := "xsep", ^.data := "2", ^.id := "box2", ^.title := "Phat sen ma ma (nouilles jaunes) sautées aux crevettes",
        <.label( ^.classes := "hiddenAcc", ^.forid :="option2","Phat sen ma ma (nouilles jaunes) sautées aux crevettes"),
        <.input( ^.id := "option2", ^.name :="p", ^.tpe :="checkbox")),
      <.td( ^.classes := "xsep", ^.data := "3", ^.id := "box3", ^.title := "Veg - Tofu sauté aux légumes et graines de soja",
        <.label( ^.classes := "hiddenAcc", ^.forid :="option3",Veg - Tofu sauté aux légumes et graines de soja),
        <.input( ^.id := "option3", ^.name :="p", ^.tpe :="checkbox")),
      <.td( ^.classes := "", ^.data := "4", ^.id := "box4", ^.title := "Soupe de nouilles de riz au porc (CH)",
        <.label( ^.classes := "hiddenAcc", ^.forid :="option4","Soupe de nouilles de riz au porc (CH)"),
        <.input( ^.id := "option4", ^.name :="p", ^.tpe :="checkbox"))),
    <.tr( ^.classes := "sums",
      <.td( ^.classes := "nonHeader"),
      <.td( ^.classes := " ",  "0" ),
      <.td( ^.classes := " ",
        <.b( "2" )),
      <.td( ^.classes := " ", "0" ),
      <.td( ^.classes := " ", "0" ),
      <.td( ^.classes := " ", "0" )
    )
  )
)
